"""
Sample Renderer Plugin: HTML Renderer

Renders the optimized prompt as a styled HTML document
that can be opened in any browser or embedded in a web view.
"""

import sys
import os
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from src.plugins.base import KiratorPlugin, kirator_plugin


@kirator_plugin(
    plugin_type="renderer",
    plugin_id="renderer_html",
    name="HTML Document Renderer",
    version="1.0.0",
    description="Renders the final prompt as a styled, copy-paste-ready HTML document.",
    author="Kirator Team",
)
class HTMLRenderer(KiratorPlugin):

    def activate(self):
        pass

    def deactivate(self):
        pass

    def render(self, prompt: str, report: dict, strategy: dict, stats: dict):
        """Return HTML string or None to defer."""
        import html as html_mod

        safe_prompt = html_mod.escape(prompt).replace("\n", "<br>")

        score = report.get("overall_score", "N/A") if isinstance(report, dict) else "N/A"

        # Quality bars
        bars = ""
        axes = [
            ("Clarity", "clarity_structure"),
            ("Linguistic", "linguistic_quality"),
            ("Fairness", "fairness_bias"),
            ("Completeness", "completeness"),
            ("Specificity", "specificity"),
            ("Ambiguity", "ambiguity"),
            ("Constraints", "constraint_clarity"),
            ("Model Compat", "model_compatibility"),
        ]
        if isinstance(report, dict):
            for label, key in axes:
                val = report.get(key, 3)
                pct = (val / 5) * 100
                color = "#4ade80" if val >= 4 else "#fbbf24" if val >= 3 else "#ef4444"
                bars += f'<div class="bar-row"><span class="bar-label">{label}</span>'
                bars += f'<div class="bar-track"><div class="bar-fill" style="width:{pct}%;background:{color}"></div></div>'
                bars += f'<span class="bar-val">{val}/5</span></div>\n'

        techs = ""
        if isinstance(strategy, dict):
            tech_list = strategy.get("selected_techniques", [])
            for t in tech_list:
                name = t.get("name", str(t)) if isinstance(t, dict) else (t.name if hasattr(t, "name") else str(t))
                techs += f'<span class="tech-badge">{name}</span> '

        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        return f'''<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Kirator Prompt</title>
<style>
body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0a0a0a; color: #e5e5e5; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
h1 {{ color: #4ade80; font-size: 24px; border-bottom: 2px solid #22c55e; padding-bottom: 8px; }}
.score {{ font-size: 48px; font-weight: 900; color: #4ade80; }}
.prompt-box {{ background: #141414; border: 1px solid #333; border-radius: 8px; padding: 20px; margin: 16px 0; white-space: pre-wrap; font-family: 'Consolas', 'Fira Code', monospace; font-size: 14px; line-height: 1.6; }}
.bar-row {{ display: flex; align-items: center; margin: 4px 0; }}
.bar-label {{ width: 100px; font-size: 12px; color: #a3a3a3; }}
.bar-track {{ flex: 1; background: #262626; border-radius: 4px; height: 8px; margin: 0 8px; }}
.bar-fill {{ height: 100%; border-radius: 4px; transition: width 0.3s; }}
.bar-val {{ width: 30px; font-size: 12px; text-align: right; color: #a3a3a3; }}
.tech-badge {{ display: inline-block; background: #1a2e1a; color: #4ade80; border: 1px solid #22c55e; border-radius: 12px; padding: 2px 10px; font-size: 12px; margin: 2px; }}
.meta {{ color: #525252; font-size: 12px; margin-top: 30px; }}
.section {{ margin: 20px 0; }}
.section h2 {{ font-size: 16px; color: #a3a3a3; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 1px; }}
</style></head><body>
<h1>KIRATOR OPTIMIZED PROMPT</h1>
<div class="section"><div class="score">{score}<span style="font-size:20px;color:#a3a3a3">/100</span></div></div>
<div class="section"><h2>Techniques Used</h2><div>{techs}</div></div>
<div class="section"><h2>Quality Breakdown</h2>{bars}</div>
<div class="section"><h2>Final Prompt</h2><div class="prompt-box">{safe_prompt}</div></div>
<div class="meta">Generated by Kirator Prompt Factory v2.0 at {ts}</div>
</body></html>'''